name: Auto AI Orchestrator

on:
  workflow_dispatch: {}
  schedule:
    - cron: '30 23 * * *'  # 08:30 Asia/Seoul (UTC+9) = 23:30 UTC (전날)

jobs:
  run-orchestrator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm i

      - name: Run orchestrator
        env:
          LOG_TO_CONSOLE: ${{ secrets.LOG_TO_CONSOLE }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ANTHROPIC_MODEL: ${{ secrets.ANTHROPIC_MODEL }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GEMINI_MODEL: ${{ secrets.GEMINI_MODEL }}
          MIDJOURNEY_WEBHOOK_URL: ${{ secrets.MIDJOURNEY_WEBHOOK_URL }}
        run: npm run start
