{
  "name": "creative-maru-email-automation",
  "version": "1.0.0",
  "description": "크리에이티브마루 지원사업 자동 메일링 시스템",
  "main": "send-email.js",
  "scripts": {
    "start": "node send-email.js",
    "test": "node send-email.js"
  },
  "dependencies": {
    "googleapis": "^118.0.0",
    "nodemailer": "^6.9.3"
  },
  "keywords": [
    "gmail-api",
    "nodemailer", 
    "automation",
    "email"
  ],
  "author": "크리에이티브마루",
  "license": "MIT"
}
