# .github/workflows/send-email.yml
name: 크리에이티브마루 지원사업 메일링

on:
  # 수동 실행
  workflow_dispatch:
  # 자동 스케줄 (여러 시간대 설정으로 안정성 확보)
  schedule:
    - cron: '30 0 * * *'  # UTC 00:30 = KST 09:30 (메인 실행시간)
    - cron: '0 1 * * *'   # UTC 01:00 = KST 10:00 (백업 실행시간)

jobs:
  send-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install nodemailer
        
    - name: Send Email Report
      env:
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: node send-email.js
